// Types for the Trace Library's static manifest
// (frontend/src/data/trace-library.json), generated by
// demo/seed_trace_library.py. Deliberately NOT in types/api.ts — that
// file's whole purpose is mirroring backend OpenAPI schemas, and this
// isn't one; it's a local, curated demo/eval catalog.
//
// Note what's absent: there is no `expected_category` field anywhere
// here. That's intentional and physical, not just a UI convention — the
// seed script writes expected categories only into a separate,
// eval-only file (demo/trace_library_eval.json) that nothing in the
// frontend ever imports. The hidden-until-investigated requirement is
// enforced by this type simply not having anywhere to put that field.

export type TraceLibraryEventType = "llm_call" | "tool_call";

export interface TraceLibraryEvent {
  evidence_id: string;
  type: TraceLibraryEventType;
  preview: string;
}

export interface TraceLibraryScenario {
  id: string;
  title: string;
  domain: string;
  user_request: string;
  incident_title: string;
  incident_description: string;
  project_name: string;
  session_id: string;
  events: TraceLibraryEvent[];
}
