// The container/page component. Owns state and fetch orchestration for
// both the read side (incident/investigation display) and, as of
// Sprint 16, the write side (create/link/correlate/investigate actions).
// IncidentHeader, EvidenceList, InvestigationPanel, ActionBar and the rest
// stay presentational — they render what they're given and call the
// callbacks they're passed, nothing more.
//
// UI-polish pass, three structural changes:
//   1. The page is an explicit six-stage pipeline (PipelineStages +
//      StageSection) rather than a flat stack of same-weight sections, and
//      each of the four actions lives in the stage it belongs to.
//   2. Exactly one action carries primary weight at any moment (see
//      `nextAction`), and actions that aren't meaningful for the current
//      state aren't rendered at all.
//   3. A mutation's re-fetch keeps the incident on screen. It used to drop
//      to `{status:"loading"}`, which unmounted the entire incident body on
//      every single action — including the multi-second Investigate call.

import { useEffect, useState } from "react";
import {
  getIncident,
  getInvestigations,
  createIncident,
  linkEvidence,
  correlateIncident,
  investigateIncident,
  updateIncidentStatus,
} from "../api/incidents";
import { getRemediations, requestRemediation } from "../api/investigations";
import { ApiError } from "../api/client";
import type {
  IncidentStatus,
  IncidentWithEvidenceResponse,
  InvestigationResponse,
  RemediationResponse,
} from "../types/api";
import type { TraceLibraryScenario } from "../types/traceLibrary";
import traceLibraryData from "../data/trace-library.json";
import IncidentHeader from "../components/IncidentHeader";
import EvidenceList from "../components/EvidenceList";
import InvestigationPanel, { pickMostRecentInvestigation } from "../components/InvestigationPanel";
import RemediationPanel from "../components/RemediationPanel";
import ResolutionPanel from "../components/ResolutionPanel";
import TraceLibrary from "../components/TraceLibrary";
import ActionBar, { type ActionState } from "../components/ActionBar";
import PipelineStages, { type PipelineStage, type StageState } from "../components/PipelineStages";
import StageSection from "../components/StageSection";
import ErrorBanner from "../components/ErrorBanner";
import { btnGhost, btnPrimary, btnSecondary, cardMuted, input } from "../components/ui";

// Cast is safe: this file is generated by demo/seed_trace_library.py to
// exactly match TraceLibraryScenario's shape. See that script for the
// only place expected-category evaluation metadata is written — it is
// never present in this file.
const TRACE_LIBRARY: TraceLibraryScenario[] = traceLibraryData as TraceLibraryScenario[];

// evidence id -> human-readable preview, flattened from the whole manifest
// rather than just the selected scenario, so an incident loaded by ID gets
// readable evidence too. Evidence ids are UUIDs, so there's no collision
// risk in merging every scenario into one map. Built once at module load;
// the manifest is a static import.
const EVIDENCE_PREVIEWS: Record<string, string> = {};
for (const scenario of TRACE_LIBRARY) {
  for (const event of scenario.events) {
    EVIDENCE_PREVIEWS[event.evidence_id] = event.preview;
  }
}

const DEFAULT_INCIDENT_ID = "cffefe5b-7b72-49f9-a995-9e929d4d2486";

// Three explicit states rather than a couple of loose booleans — makes
// "what should render right now" unambiguous (no accidental moment
// where both an old result and a loading spinner could show at once).
type LoadState =
  | { status: "idle" }
  | { status: "loading" }
  | { status: "error"; message: string }
  | {
      status: "success";
      incident: IncidentWithEvidenceResponse;
      investigations: InvestigationResponse[];
    };

// Shared with all four action handlers below — same ApiError-vs-network
// distinction loadIncident already used, factored out so it isn't
// duplicated five times.
function extractErrorMessage(err: unknown): string {
  return err instanceof ApiError
    ? `${err.message} (status ${err.status})`
    : "Could not reach the backend. Is it running?";
}

// Sprint 17: remediation's own small state, separate from both LoadState
// (read side) and ActionBar's ActionState (create/link/correlate/
// investigate) — the "Get Remediation" trigger is scoped to the displayed
// investigation rather than the whole incident, so it gets its own minimal
// state rather than being folded into either existing union.
//
// The fetched remediations now live in their own piece of state instead of
// inside a "success" variant, so an in-flight request no longer blanks the
// panel it's about to update.
type RemediationLoadState =
  | { status: "idle" }
  | { status: "loading" }
  | { status: "requesting" }
  | { status: "error"; message: string };

// Which single action the workflow is waiting on. Drives primary-vs-
// secondary button weight, so the recommended next step is never just one
// of several identical-looking buttons.
type NextAction = "select-trace" | "create" | "investigate" | "remediate" | "resolve" | "none";

export default function IncidentDetail() {
  const [incidentIdInput, setIncidentIdInput] = useState(DEFAULT_INCIDENT_ID);
  const [state, setState] = useState<LoadState>({ status: "idle" });
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [actionState, setActionState] = useState<ActionState>({ status: "idle" });
  const [remediationState, setRemediationState] = useState<RemediationLoadState>({ status: "idle" });
  const [remediations, setRemediations] = useState<RemediationResponse[]>([]);
  const [statusActionState, setStatusActionState] = useState<
    { status: "idle" } | { status: "changing" } | { status: "error"; message: string }
  >({ status: "idle" });
  const [selectedScenarioId, setSelectedScenarioId] = useState<string | null>(null);
  // Which scenario the currently loaded incident was created from, so the
  // Create Incident stage can collapse to a summary once it's been acted on
  // and re-open if a different trace is picked.
  const [createdFromScenarioId, setCreatedFromScenarioId] = useState<string | null>(null);
  const [forceCreateForm, setForceCreateForm] = useState(false);
  const [showIdLoader, setShowIdLoader] = useState(false);

  // The selected Trace Library scenario, if any. Drives both ActionBar's
  // prefill and the seed evidence sent with Create Incident below.
  const selectedScenario = TRACE_LIBRARY.find((s) => s.id === selectedScenarioId) ?? null;

  async function loadIncident(
    id: string,
    // keepCurrent: this is a re-fetch after a mutation, so hold the current
    // incident on screen and flag a refresh instead of unmounting it.
    // isAutoLoad: the first-mount load of DEFAULT_INCIDENT_ID.
    opts: { keepCurrent?: boolean; isAutoLoad?: boolean } = {},
  ) {
    const trimmedId = id.trim();
    if (!trimmedId) {
      setState({ status: "error", message: "Enter an incident ID." });
      return;
    }

    if (opts.keepCurrent) {
      setIsRefreshing(true);
    } else {
      setState({ status: "loading" });
    }

    try {
      // Two independent GETs. Run them together rather than sequentially —
      // neither depends on the other's result, so there's no reason to
      // wait on one before starting the next.
      const [incident, investigations] = await Promise.all([
        getIncident(trimmedId),
        getInvestigations(trimmedId),
      ]);
      setState({ status: "success", incident, investigations });
    } catch (err) {
      // A 404 on the auto-loaded demo incident just means this database was
      // reset since trace-library.json was seeded. That's an expected state,
      // not a failure worth opening the app on a red banner — fall through
      // to the "pick a trace to begin" state instead. Anything else (backend
      // down, 500) still surfaces as a real error.
      if (opts.isAutoLoad && err instanceof ApiError && err.status === 404) {
        setState({ status: "idle" });
      } else {
        setState({ status: "error", message: extractErrorMessage(err) });
      }
    } finally {
      setIsRefreshing(false);
    }
  }

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    loadIncident(incidentIdInput);
  }

  // Load the verified demo incident on first mount, so opening the app
  // shows the real workflow immediately rather than an empty idle state.
  // Still fully re-triggerable via the ID loader below for any other ID.
  useEffect(() => {
    loadIncident(DEFAULT_INCIDENT_ID, { isAutoLoad: true });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // --- Sprint 17: remediation ---------------------------------------------

  async function loadRemediations(investigationId: string) {
    setRemediationState({ status: "loading" });
    try {
      const fetched = await getRemediations(investigationId);
      setRemediations(fetched);
      setRemediationState({ status: "idle" });
    } catch (err) {
      setRemediationState({ status: "error", message: extractErrorMessage(err) });
    }
  }

  // Whenever the incident finishes loading and there's a most-recent
  // investigation to show, also load whatever remediations already exist
  // for it — same mirroring relationship investigations already have to
  // the incident load. If there's no investigation yet, remediation has
  // nothing to target, so state stays idle.
  useEffect(() => {
    if (state.status !== "success") return;
    const investigation = pickMostRecentInvestigation(state.investigations);
    if (investigation) {
      loadRemediations(investigation.id);
    } else {
      setRemediations([]);
      setRemediationState({ status: "idle" });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [state]);

  async function handleGetRemediation() {
    if (state.status !== "success") return;
    const investigation = pickMostRecentInvestigation(state.investigations);
    if (!investigation) return;

    setRemediationState({ status: "requesting" });
    try {
      await requestRemediation(investigation.id);
      await loadRemediations(investigation.id);
    } catch (err) {
      setRemediationState({ status: "error", message: extractErrorMessage(err) });
    }
  }

  // --- Sprint 16: write actions ------------------------------------------
  // Each follows the same shape: set an in-flight actionState, call the
  // corresponding api/incidents.ts function, then re-fetch via the
  // existing loadIncident() rather than merging the mutation's own
  // response into local state (per the Sprint 16 plan, section 6).
  // The error variant now carries the action's name so the single
  // page-level ErrorBanner can label what failed.

  async function handleCreateIncident(data: {
    projectName: string;
    title: string;
    description: string;
  }) {
    setActionState({ status: "creating" });
    try {
      const created = await createIncident({
        project_name: data.projectName,
        title: data.title,
        description: data.description || null,
        // Trace Library path: the scenario's events are its full
        // evidence set, so linking and correlating them is a mechanical
        // consequence of the selection. The backend does it inside the
        // create transaction (incident_service.create_incident) — no
        // separate link/correlate calls needed. Undefined for the manual
        // path, which sends no seed evidence and stays on the separate
        // Link/Correlate actions.
        evidence_ids: selectedScenario?.events.map((e) => e.evidence_id),
      });
      setIncidentIdInput(created.id);
      setCreatedFromScenarioId(selectedScenario?.id ?? null);
      setForceCreateForm(false);
      await loadIncident(created.id);
      setActionState({ status: "idle" });
    } catch (err) {
      setActionState({
        status: "error",
        action: "Creating the incident",
        message: extractErrorMessage(err),
      });
    }
  }

  async function handleLinkEvidence(evidenceIds: string[]) {
    setActionState({ status: "linking" });
    try {
      await linkEvidence(incidentIdInput, evidenceIds);
      await loadIncident(incidentIdInput, { keepCurrent: true });
      setActionState({ status: "idle" });
    } catch (err) {
      setActionState({
        status: "error",
        action: "Linking evidence",
        message: extractErrorMessage(err),
      });
    }
  }

  async function handleCorrelate() {
    setActionState({ status: "correlating" });
    try {
      await correlateIncident(incidentIdInput);
      await loadIncident(incidentIdInput, { keepCurrent: true });
      setActionState({ status: "idle" });
    } catch (err) {
      setActionState({ status: "error", action: "Correlation", message: extractErrorMessage(err) });
    }
  }

  async function handleInvestigate() {
    setActionState({ status: "investigating" });
    try {
      await investigateIncident(incidentIdInput);
      await loadIncident(incidentIdInput, { keepCurrent: true });
      setActionState({ status: "idle" });
    } catch (err) {
      setActionState({ status: "error", action: "Investigation", message: extractErrorMessage(err) });
    }
  }

  // --- Sprint 18: status update --------------------------------------------
  // Same shape as every other action handler: set an in-flight state,
  // call the API function, then re-fetch via loadIncident() so the badge
  // reflects the backend's actual, confirmed state — never optimistically
  // assumed from the request that was sent.

  async function handleChangeStatus(status: IncidentStatus) {
    setStatusActionState({ status: "changing" });
    try {
      await updateIncidentStatus(incidentIdInput, status);
      await loadIncident(incidentIdInput, { keepCurrent: true });
      setStatusActionState({ status: "idle" });
    } catch (err) {
      setStatusActionState({ status: "error", message: extractErrorMessage(err) });
    }
  }

  // --- Derived view state --------------------------------------------------

  const incident = state.status === "success" ? state.incident : null;
  const investigations = state.status === "success" ? state.investigations : [];
  const investigation = pickMostRecentInvestigation(investigations);

  const hasEvidence = (incident?.evidence.length ?? 0) > 0;
  const hasInvestigation = investigation !== null;
  const hasRemediation = remediations.length > 0;
  const isResolved = incident?.status === "resolved";
  const isBusy = actionState.status !== "idle" && actionState.status !== "error";

  // Re-open the create stage when there's nothing loaded, when the user
  // explicitly asks for it, or when they've picked a trace other than the
  // one this incident came from (otherwise the selection would look inert).
  const scenarioChanged =
    selectedScenarioId !== null && selectedScenarioId !== createdFromScenarioId;
  const showCreateForm = incident === null || forceCreateForm || scenarioChanged;

  const nextAction: NextAction =
    !incident && !selectedScenario
      ? "select-trace"
      : showCreateForm
        ? "create"
        : isResolved
          ? "none"
          : !hasInvestigation
            ? "investigate"
            : !hasRemediation
              ? "remediate"
              : "resolve";

  const stageStates: Record<
    "trace" | "incident" | "evidence" | "diagnosis" | "remediation" | "resolved",
    StageState
  > = {
    trace: selectedScenario || incident ? "done" : "current",
    incident: incident && !showCreateForm ? "done" : nextAction === "create" ? "current" : "pending",
    evidence: hasEvidence ? "done" : incident ? "current" : "pending",
    diagnosis: hasInvestigation ? "done" : nextAction === "investigate" ? "current" : "pending",
    remediation: hasRemediation ? "done" : nextAction === "remediate" ? "current" : "pending",
    resolved: isResolved ? "done" : nextAction === "resolve" ? "current" : "pending",
  };

  const stages: PipelineStage[] = [
    { label: "Trace", state: stageStates.trace },
    { label: "Incident", state: stageStates.incident },
    { label: "Evidence", state: stageStates.evidence },
    { label: "Diagnosis", state: stageStates.diagnosis },
    { label: "Remediation", state: stageStates.remediation },
    { label: "Resolved", state: stageStates.resolved },
  ];

  // One banner for every failure, always labelled with the action that
  // produced it. This replaces four identically-styled inline boxes that
  // appeared in four different positions with no indication of which action
  // had actually broken.
  const failure =
    state.status === "error"
      ? { action: "Loading the incident", message: state.message }
      : actionState.status === "error"
        ? { action: actionState.action, message: actionState.message }
        : statusActionState.status === "error"
          ? { action: "Changing the status", message: statusActionState.message }
          : remediationState.status === "error"
            ? { action: "Remediation", message: remediationState.message }
            : null;

  function dismissFailure() {
    if (state.status === "error") setState({ status: "idle" });
    if (actionState.status === "error") setActionState({ status: "idle" });
    if (statusActionState.status === "error") setStatusActionState({ status: "idle" });
    if (remediationState.status === "error") setRemediationState({ status: "idle" });
  }

  return (
    <div className="mx-auto max-w-4xl px-6 py-10">
      {state.status === "loading" && (
        <p className="text-sm text-slate-500">Loading incident…</p>
      )}

      {state.status !== "loading" && (
        <div className="space-y-8">
          {incident && <IncidentHeader incident={incident} isRefreshing={isRefreshing} />}

          <PipelineStages stages={stages} />

          {failure && (
            <ErrorBanner
              action={failure.action}
              message={failure.message}
              onDismiss={dismissFailure}
            />
          )}

          {!incident && state.status === "idle" && (
            <div className={`${cardMuted} px-4 py-3`}>
              <p className="text-sm text-slate-400">
                Pick a trace below to begin, or load an existing incident by ID at the bottom of the
                page.
              </p>
            </div>
          )}

          <StageSection
            step={1}
            title="Select Trace"
            hint="Curated example agent executions for exploring the investigation workflow — not live production traffic."
            done={stageStates.trace === "done"}
          >
            <TraceLibrary
              scenarios={TRACE_LIBRARY}
              selectedId={selectedScenarioId}
              onSelect={(scenario) => setSelectedScenarioId(scenario.id)}
              collapsed={Boolean(incident) && !showCreateForm}
            />
          </StageSection>

          <StageSection
            step={2}
            title="Create Incident"
            hint={
              selectedScenario
                ? "The selected trace determines the evidence, so it's attached and correlated automatically — there's nothing to link by hand."
                : "Details are free-form on this path, and evidence is linked and correlated as explicit steps."
            }
            done={stageStates.incident === "done"}
            pending={stageStates.incident === "pending"}
          >
            {showCreateForm ? (
              <ActionBar
                hasLoadedIncident={incident !== null}
                onCreateIncident={handleCreateIncident}
                onLinkEvidence={handleLinkEvidence}
                onCorrelate={handleCorrelate}
                actionState={actionState}
                isNextAction={nextAction === "create"}
                prefill={
                  selectedScenario
                    ? {
                        scenarioId: selectedScenario.id,
                        projectName: selectedScenario.project_name,
                        title: selectedScenario.incident_title,
                        description: selectedScenario.incident_description,
                      }
                    : undefined
                }
                scenarioEvidence={
                  selectedScenario
                    ? selectedScenario.events.map((e) => ({
                        id: e.evidence_id,
                        type: e.type,
                        preview: e.preview,
                      }))
                    : undefined
                }
              />
            ) : (
              <div className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-slate-800 bg-slate-900/40 px-4 py-3">
                <p className="text-xs text-slate-400">
                  Created {incident && new Date(incident.created_at).toLocaleString()} ·{" "}
                  {incident?.evidence.length ?? 0} evidence events attached automatically
                </p>
                <button
                  type="button"
                  onClick={() => setForceCreateForm(true)}
                  className={`${btnGhost} shrink-0`}
                >
                  Create another
                </button>
              </div>
            )}
          </StageSection>

          <StageSection
            step={3}
            title={`Evidence${hasEvidence ? ` (${incident?.evidence.length})` : ""}`}
            hint="Linked and correlated automatically when the incident was created. Correlation may add related events from the same ±30s window."
            done={stageStates.evidence === "done"}
            pending={stageStates.evidence === "pending"}
          >
            <EvidenceList evidence={incident?.evidence ?? []} previews={EVIDENCE_PREVIEWS} />
          </StageSection>

          <StageSection
            step={4}
            title="Investigation"
            hint="Classifies the incident against the taxonomy and explains the root cause, citing the evidence it used."
            done={stageStates.diagnosis === "done"}
            pending={stageStates.diagnosis === "pending"}
            action={
              // Only meaningful while there's an unresolved incident to
              // investigate. Re-running is genuinely useful (it snapshots a
              // fresh diagnosis against current evidence), so it stays —
              // but it drops to secondary weight and says what it does.
              incident && !isResolved ? (
                <button
                  type="button"
                  onClick={() => handleInvestigate()}
                  disabled={isBusy}
                  className={nextAction === "investigate" ? btnPrimary : btnSecondary}
                >
                  {actionState.status === "investigating"
                    ? "Investigating…"
                    : hasInvestigation
                      ? "Re-run"
                      : "Investigate"}
                </button>
              ) : undefined
            }
          >
            <InvestigationPanel
              investigations={investigations}
              evidence={incident?.evidence ?? []}
              previews={EVIDENCE_PREVIEWS}
            />
          </StageSection>

          <StageSection
            step={5}
            title="Remediation"
            hint="An advisory recommended fix derived from the diagnosis above."
            done={stageStates.remediation === "done"}
            pending={stageStates.remediation === "pending"}
            action={
              hasInvestigation && !isResolved ? (
                <button
                  type="button"
                  onClick={handleGetRemediation}
                  disabled={remediationState.status === "requesting" || isBusy}
                  className={nextAction === "remediate" ? btnPrimary : btnSecondary}
                >
                  {remediationState.status === "requesting"
                    ? "Generating…"
                    : hasRemediation
                      ? "Regenerate"
                      : "Get Remediation"}
                </button>
              ) : undefined
            }
          >
            <RemediationPanel
              remediations={remediations}
              pending={
                remediationState.status === "requesting"
                  ? "generating"
                  : remediationState.status === "loading"
                    ? "loading"
                    : "none"
              }
              isAvailable={hasInvestigation}
            />
          </StageSection>

          <StageSection
            step={6}
            title="Resolve"
            hint="Status is always a human decision — nothing here changes on its own."
            done={stageStates.resolved === "done"}
            pending={stageStates.resolved === "pending" && !incident}
          >
            {incident ? (
              <ResolutionPanel
                status={incident.status}
                resolvedAt={incident.resolved_at}
                hasInvestigation={hasInvestigation}
                isNextAction={nextAction === "resolve"}
                isChangingStatus={statusActionState.status === "changing"}
                onChangeStatus={handleChangeStatus}
              />
            ) : (
              <div className={`${cardMuted} px-4 py-3`}>
                <p className="text-sm text-slate-500">Unlocks once an incident exists.</p>
              </div>
            )}
          </StageSection>

          {/* Developer utility, deliberately last. This used to be the very
              first element on the page, which framed a raw UUID field as the
              product's entry point. */}
          <div className="border-t border-slate-800 pt-4">
            {showIdLoader ? (
              <form onSubmit={handleSubmit} className="flex gap-2">
                <input
                  type="text"
                  value={incidentIdInput}
                  onChange={(e) => setIncidentIdInput(e.target.value)}
                  placeholder="Incident ID"
                  className={`${input} font-mono`}
                />
                <button type="submit" className={`${btnSecondary} shrink-0`}>
                  Load
                </button>
              </form>
            ) : (
              <button type="button" onClick={() => setShowIdLoader(true)} className={btnGhost}>
                Load an existing incident by ID
              </button>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
